name: Gist Sync Multiple Userscripts

on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - '.gitattributes'
      - '.gitignore'
  workflow_dispatch:

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rclone
        uses: BenjiThatFoxGuy/setup-bclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG_B64 }}
      - name: Copy assets to cloud storage
        run: |
          echo "Copying release assets to r2:updates"
          rclone copy nitter-redirect/ r2:updates --progress --checksum -v
          rclone copy vrcw.net/ r2:updates --progress --checksum -v
          rclone copy nexusmods.com/ r2:updates --progress --checksum -v
          rclone copy e621.net/ r2:updates --progress --checksum -v
          rclone copy youtube.com/ r2:updates --progress --checksum -v
          rclone copy twitchemotes.com/ r2:updates --progress --checksum -v
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
            cf_zone: ${{ secrets.CF_ZONE_ID }}
            cf_auth: ${{ secrets.CF_API_TOKEN }}
            hosts: |
              updates.benjifox.gay
            files: |
              https://updates.benjifox.gay/nitter-redirect.user.js
              https://updates.benjifox.gay/nitter-redirect.meta.js
              https://updates.benjifox.gay/vrcw.net.user.js
              https://updates.benjifox.gay/vrcw.net.meta.js
              https://updates.benjifox.gay/nexusmods.com.user.js
              https://updates.benjifox.gay/nexusmods.com.meta.js
              https://updates.benjifox.gay/e621.net.user.js
              https://updates.benjifox.gay/e621.net.meta.js
              https://updates.benjifox.gay/youtube.com.user.js
              https://updates.benjifox.gay/youtube.com.meta.js
              https://updates.benjifox.gay/twitchemotes.com.user.js
              https://updates.benjifox.gay/twitchemotes.com.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/e0806551d65f884121e26e8774e05d5b
          gist_title: nitter-redirect.user.js
          gist_description: Automatically redirect from Twitter/X to Nitter, automatically choosing a Nitter instance based on which one has the current post/user available.
          github_file: nitter-redirect/nitter-redirect.user.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-2
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/e0806551d65f884121e26e8774e05d5b
          gist_title: nitter-redirect.meta.js
          gist_description: Automatically redirect from Twitter/X to Nitter, automatically choosing a Nitter instance based on which one has the current post/user available.
          github_file: nitter-redirect/nitter-redirect.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-3
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/42c48f58c9b33f36d9cdec3c087ce307
          gist_title: vrcw.net.user.js
          gist_description: Converts VRChat world IDs to VRCX deeplinks on vrcw.net
          github_file: vrcw.net/vrcw.net.user.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-4
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/42c48f58c9b33f36d9cdec3c087ce307
          gist_title: vrcw.net.meta.js
          gist_description: Converts VRChat world IDs to VRCX deeplinks on vrcw.net
          github_file: vrcw.net/vrcw.net.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-5
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/bb455626a00616ccb5d48c5384be7455
          gist_title: nexusmods.com.user.js
          gist_description: Automatically clicks the "Slow Download" button on Nexus Mods download pages.
          github_file: nexusmods.com/nexusmods.com.user.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-6
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/bb455626a00616ccb5d48c5384be7455
          gist_title: nexusmods.com.meta.js
          gist_description: Automatically clicks the "Slow Download" button on Nexus Mods download pages.
          github_file: nexusmods.com/nexusmods.com.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-7
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/5a0576874212dc22aabc39c7f24b1c40
          gist_title: e621.net.user.js
          gist_description: Restore deleted e621/e926 posts from archive if available
          github_file: e621.net/e621.net.user.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-8
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/5a0576874212dc22aabc39c7f24b1c40
          gist_title: e621.net.meta.js
          gist_description: Restore deleted e621/e926 posts from archive if available
          github_file: e621.net/e621.net.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-9
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/256aa1295714ee5424e4e20bf155fdcd
          gist_title: youtube.com.user.js
          gist_description: Removes list=WL from video links on your Watch Later playlist page so videos open solo and can be ticked off.
          github_file: youtube.com/youtube.com.user.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-10
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/256aa1295714ee5424e4e20bf155fdcd
          gist_title: youtube.com.meta.js
          gist_description: Removes list=WL from video links on your Watch Later playlist page so videos open solo and can be ticked off.
          github_file: youtube.com/youtube.com.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-11
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/22be2e2bf8b0ac8f5340fcaa43e63cdf
          gist_title: twitchemotes.com.meta.js
          gist_description: Unblocks right-click on emote and badge images. If they'd just give us a "don't show again" option, we wouldn't need this—just respect the owners. Popup begone!
          github_file: twitchemotes.com/twitchemotes.com.meta.js
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-12
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/BenjiThatFoxGuy/22be2e2bf8b0ac8f5340fcaa43e63cdf
          gist_title: twitchemotes.com.meta.js
          gist_description: Unblocks right-click on emote and badge images. If they'd just give us a "don't show again" option, we wouldn't need this—just respect the owners. Popup begone!
          github_file: twitchemotes.com/twitchemotes.com.meta.js